function sim_spec = getSimSpec(NdeepRS, NdeepFS)

i = 0;

% % % % % % % % % % % % % % Deep RS cells % % % % % % % % % % % % % % % % %
    
i = i+1;
spec.populations(i).name = 'deepRS';
spec.populations(i).size = NdeepRS; % 1;
spec.populations(i).equations = {['V''=(I_const+@current)/Cm; V(0)=' num2str(-65) '; monitor functions; monitor V.spikes(0);']};
spec.populations(i).mechanism_list = {'iNaP','iKs','iKsConst','iKDRG','iNaG','iLeak',...
    'CaDynT','iCaT','iKCaT','iPeriodicPulsesBen','itonic', 'iSpeechInput', 'iVariedPulses'}; %,'iFMPulses'}; %,...'iCarracedoEPSPs'}; % 'iSpikeTriggeredPulse',, 'VaryRandomSeed'}; % 'iPeriodicSpikes',
spec.populations(i).parameters = {...
    'Cm', 2.7, 'PPstim', 0, 'gSpike', 0, 'PPcenter', 0, 'PPnorm', 0,...
    'gKs', 1.4472, 'gNaP', 0.4307, 'gKCa', 0.1512, 'bKCa', .002,...
    'gCa', 0.54, 'CAF', 2.2222,...
    'gl', 0.27, 'gNa', 125, 'gKDR', 54, 'tau_h', 5, 'tau_m', 5,...
    'I_const', 0, 'ton', 500, 'toff', Inf, 'Iapp', -9.2, 'Inoise', 0.01,...                                         %  (ton<t&t<toff) %%% 'PPstim = 0; PPfreq = 1.5; PPwidth = floor((1000/PPfreq)/4); PPshift = 0; ap_pulse_num = 0; kernel_type = 7;',... % in ms
    'PPonset', 10, 'gCar', 0,... % 'STPstim',0, 'dsfact',dsfact,...
    };
% spec.populations(i).parameters = {...
%     'Cm',Cm_Ben,'PPstim',deepRSPPstim,'gSpike',deepRSgSpike,'PPcenter',0,'PPnorm',0,...
%     'gKs',gKs,'gKCs',0,'gNaP',gKs/gNaP_denom,'gKCa',gKCa,'bKCa',bKCa,'gCa',gCa,'CAF',CAF,...
%     'gl',gl_dRS,'gNa',gNa_dRS,'gKDR',gKDR_dRS,...
%     'I_const',I_const,'tau_h',tau_fast,'tau_m',tau_fast,...
%     'ton',500,'toff',tspan(end),'I_app',JdeepRS,'Inoise',0,...                                         %  (ton<t&t<toff) %%% 'PPstim = 0; PPfreq = 1.5; PPwidth = floor((1000/PPfreq)/4); PPshift = 0; ap_pulse_num = 0; kernel_type = 7;',... % in ms
%     'PPonset',PPonset,'gCar',0,... % 'STPstim',0, 'dsfact',dsfact,...
%     'gSpeech', 0,...
%     'VPstim', 0,...
%     };

if NdeepFS > 0

% % % % % % % % % % % % % % Deep FS cells % % % % % % % % % % % % % % % % %
    
    i=i+1;
    spec.populations(i).name = 'deepFS';
    spec.populations(i).size = NdeepFS; % 1;
    spec.populations(i).equations = {['V''=(@current)/Cm; V(0)=' num2str(-65) '; monitor functions;']};
    spec.populations(i).mechanism_list = {'IBitonic','IBnoise','FSiNaF','FSiKDR','IBleak','iSpeechInput'};
    spec.populations(i).parameters = {...
        'V_IC', -65, 'IC_noise', 0, 'Cm', 0.9, 'E_l', -70, 'g_l', 0.1,...
        'stim', 0.95, 'onset', 0, 'offset', Inf,...
        'V_noise', 0,...
        'gNaF', 100, 'E_NaF', 50,...
        'gKDR', 80, 'E_KDR', -95,...
        };
    %     spec.populations(i).parameters = {...
    %         'V_IC',-65,'IC_noise',IC_noise,'Cm',Cm,'E_l',-67,'g_l',0.1,...
    %         'stim',deepJfs,'onset',0,'offset',Inf,...
    %         'V_noise',deepFS_Vnoise,...
    %         'gNaF',100,'E_NaF',ENa,...
    %         'gKDR',80,'E_KDR',E_EKDR,...
    %         'gSpeech', 0,...
    %         };

% % % % % % % % % % % %  Connections  % % % % % % % % % % % % % %

    i=0;

    % % deepRS->deepFS synaptic connection
    i=i+1;
    spec.connections(i).direction = 'deepRS->deepFS';
    spec.connections(i).mechanism_list = {'IBaIBdbiSYNseed'};
    spec.connections(i).parameters = {'g_SYN', 0.075, 'E_SYN', 0,'tauDx', 2.5,...
        'tauRx', 0.25, 'fanout', 0, 'IC_noise', 0, 'g_SYN_hetero', 0,...
        };
    %     spec.connections(i).parameters = {'g_SYN',gAMPA_deepRSdeepFS,'E_SYN',EAMPA,'tauDx',tauAMPAd,...
    %         'tauRx',tauAMPAr,'fanout',0,'IC_noise',0,'g_SYN_hetero',gsyn_hetero, ...
    %         };

    % % deepFS->deepRS Synaptic connections
    i=i+1;
    spec.connections(i).direction = 'deepFS->deepRS';                  
    spec.connections(i).mechanism_list = {'IBaIBdbiSYNseed'};
    spec.connections(i).parameters = {'g_SYN', 0.15, 'E_SYN', -95, 'tauDx', 50,...
        'tauRx', 0.25, 'fanout', 0, 'IC_noise', 0, 'g_SYN_hetero', 0,...
        };
    %     spec.connections(i).parameters = {'g_SYN',gGABAa_deepFSdeepRS,'E_SYN',EGABA,'tauDx',tauGABAad,...
    %         'tauRx',tauGABAar,'fanout',0,'IC_noise',0,'g_SYN_hetero',gsyn_hetero,...
    %         };
    
end

sim_spec = spec;

end