function sim_struct = init_sim_struct(varargin)

keys = {'tspan', 'sim_mode', 'pulse_mode',...
    'save_data_flag', 'verbose_flag', 'parallel_flag', 'num_cores', 'compile_flag', 'cluster_flag', 'qsub_mode', 'overwrite_flag', 'one_solve_file_flag',...
    'debug_flag', 'analysis_functions', 'analysis_options',...'dt',dt,'downsample_factor',dsfact,'solver',solver,'coder',0,... % [data, ~, result]
    'include_deepRS', 'include_deepFS',...
    };

values = {[0 6000], 1, 0,...
    0, 1, 1, 16, 0, 0, 'array', 1, 1,...
    0,{},{},...
    1, 0,...
    };

sim_struct = init_struct(keys, values, varargin{:});